### ISSUE TITLE
nginx error

### ISSUE THREAD

**Issue by metallicats** [bmcgonag/Vector#10]
wireguard-sg systemd[1]: Starting A high performance web server and a reverse proxy server...
Apr 24 14:14:44 wireguard-sg systemd[1]: nginx.service: Failed to parse PID from file /run/nginx.pid: Invalid argum
Apr 24 14:14:44 wireguard-sg systemd[1]: Started A high performance web server and a reverse proxy server.
lines 1-13/13 (END)

**Comment by metallicats** [comment]
I was able to get the error away by commenting out 
#sudo service nginx status

but then I got another error

**Comment by bmcgonag** [comment]
Hey @metallicats - the status check is for this very reason.  It's there to make sure Nginx is installed, configured, and running as expected.  So, I wouldn't remove that line, as it has indicated correctly an error.  

In searching around I found this:

"

That pid error is often simply caused by restarting Nginx when it isn’t started in the first place. Though the init script should be smart enough to fall back from restart to start. So I don’t think that’s the real problem here. Check to see that Nginx is running and the port that it is listening on by running: `netstat -plunt | grep nginx`

On Fedora 20, firewalld is running by default. Have you opened port 80?

If the netstat output shows that it is running, then the firewall is most likely your problem. To open the port, run:

`firewall-cmd --permanent --zone=public --add-service=http`
`systemctl restart firewalld.service` "
